# Generated by Django 3.2.8 on 2021-10-16 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pages', models.IntegerField(null=True)),
                ('published', models.BooleanField(default=True)),
                ('publication_date', models.DateField(null=True)),
                ('edition', models.IntegerField(null=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ManyToManyField(related_name='books', to='autors.Autor')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorials.editorial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
